
spring:
  application:
    name:saller_ruijie
  datasource:
    url: jdbc:mysql://localhost:3306/saller?useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    configuration:
      #这里主要为了配置，驼峰名法，如果表名是下划线
      map-underscore-to-camel-case:true
      log-impl:org.apache.ibtais.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type:ASSIGN_ID
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: 1ms
        max-idle: 4
rejgi:
      path: D:/
server:
  port: 8081




